inherit_from:
  - ../hitobito/.rubocop.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - Rakefile
    - Gemfile
    - db/**/*
    - config/**/*
    - bin/**/*
    - tmp/**/*

# core sets belongs_to_required_by_default = false so this is not redundant
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false
