name: "Rails Test"

on:
  push:
    branches: ["develop", "main"]
  pull_request:

env:
  RAILS_DB_ADAPTER: postgresql
  RAILS_DB_HOST: 127.0.0.1
  RAILS_DB_PORT: 5432
  RAILS_DB_USERNAME: hitobito
  RAILS_DB_PASSWORD: hitobito
  RAILS_DB_NAME: hitobito_test
  RAILS_TEST_DB_NAME: hitobito_test
  RAILS_ENV: test

jobs:
  wagon_specs:
    name: specs
    runs-on: "ubuntu-24.04"
    env:
      DISABLE_TEST_SCHEMA_MAINTENANCE: true
      HEADLESS: true

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: hitobito
          POSTGRES_PASSWORD: hitobito
          POSTGRES_DB: hitobito_test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U hitobito"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: "Install OS deps"
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y libvips42 direnv

      - uses: ruby/setup-ruby@v1
        with:
          working-directory: hitobito
          bundler-cache: true

      - uses: actions/setup-node@v6
        with:
          node-version-file: hitobito/.tool-versions
          cache: 'yarn'
          cache-dependency-path: hitobito/yarn.lock

      - run: yarn install --frozen-lockfile
        working-directory: hitobito

      - name: "Copy files for wagon and update lockfile"
        run: |
          cp -v ../.envrc.example ../.envrc
          direnv allow
          cp -v ../hitobito/.tool-versions ../hitobito/Gemfile.lock ./
          bundle lock
        working-directory: hitobito_bienenschweiz

      - uses: ruby/setup-ruby@v1
        with:
          working-directory: hitobito_bienenschweiz
          bundler-cache: true

      - name: "Prepare database"
        run: bundle exec rake app:db:create app:db:schema:load db:migrate
        working-directory: hitobito_bienenschweiz

      - name: "ci:setup:rspec"
        run: bundle exec rake app:ci:setup:rspec
        working-directory: hitobito_bienenschweiz

      - name: "Run specs"
        run: direnv exec bundle exec rake spec:without_features
        working-directory: hitobito_bienenschweiz

      - name: "Run Webpacker"
        run: bundle exec rake webpacker:compile
        working-directory: hitobito

      - name: "Run feature specs"
        run: bundle exec rake app:ci:setup:rspec app:spec:features:lenient
        working-directory: hitobito_bienenschweiz

      - name: "Upload capybara output"
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: capybara-output
          path: hitobito/tmp/capybara

  wagon_seeds:
    name: seeds
    runs-on: "ubuntu-24.04"
    env:
      RAILS_DB_NAME: hitobito_development
      RAILS_ENV: development

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: hitobito
          POSTGRES_PASSWORD: hitobito
          POSTGRES_DB: hitobito_development
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U hitobito"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: "Install OS deps"
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y libvips42

      - uses: ruby/setup-ruby@v1

      - name: "Activate Wagonfile.ci and update lockfile"
        run: |
          cp -v Wagonfile.ci Wagonfile
          bundle lock
        working-directory: hitobito

      - uses: ruby/setup-ruby@v1
        with:
          working-directory: hitobito
          bundler-cache: true

      - name: "Run seeds"
        run: bundle exec rake db:migrate wagon:migrate db:seed wagon:seed
        working-directory: hitobito
